version: '3'
services:
  php:
    container_name: osmirsys_phpfpm
    build: build/php
    expose:
      - '9000'
    depends_on:
      - db
    volumes:
      - ./symfony:/var/www/html/symfony:cached
      - ./logs:/var/log
  web:
    container_name: osmirsys_nginx
    build: build/nginx
    restart: always
    ports:
        - "81:80"
    depends_on:
        - php
        - db
    links:
        - db:mysql
    volumes:
        - ./symfony:/var/www/html/symfony:cached
        - ./logs:/var/log/nginx
    environment:
      - MYSQL_DATABASE=osmirsys
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=127.0.0.1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_PORT=3307
  db:
    image: mysql:5.7
    container_name: osmirsys_mysql
    environment:
      - MYSQL_DATABASE=osmirsys
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=127.0.0.1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_PORT=3307
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql