<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVgytagh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVgytagh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVgytagh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVgytagh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVgytagh\appDevDebugProjectContainer([
    'container.build_hash' => 'Vgytagh',
    'container.build_id' => 'a27d171a',
    'container.build_time' => 1554349166,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVgytagh');
