<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Manager\SecurityManager' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Util/Helper/SecurityHelperTrait.php';
include_once $this->targetDirs[3].'/src/AppBundle/Manager/SecurityManager.php';

return $this->services['AppBundle\Manager\SecurityManager'] = new \AppBundle\Manager\SecurityManager(${($_ = isset($this->services['AppBundle\Manager\UserManager']) ? $this->services['AppBundle\Manager\UserManager'] : $this->load('getUserManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'});
