<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.vqqaaby' shared service.

return $this->services['service_locator.vqqaaby'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['cycleManager' => function () {
    $f = function (\AppBundle\Manager\CycleManager $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Manager\CycleManager']) ? $this->services['AppBundle\Manager\CycleManager'] : $this->load('getCycleManagerService.php')) && false ?: '_'});
}, 'session' => function () {
    return ${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'};
}, 'tenantManager' => function () {
    $f = function (\AppBundle\Manager\TenantManager $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Manager\TenantManager']) ? $this->services['AppBundle\Manager\TenantManager'] : $this->load('getTenantManagerService.php')) && false ?: '_'});
}]);
