<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.amh2vah' shared service.

return $this->services['service_locator.amh2vah'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['authenticationUtils' => function () {
    return ${($_ = isset($this->services['security.authentication_utils']) ? $this->services['security.authentication_utils'] : $this->load('getSecurity_AuthenticationUtilsService.php')) && false ?: '_'};
}, 'manager' => function () {
    $f = function (\AppBundle\Manager\SecurityManager $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Manager\SecurityManager']) ? $this->services['AppBundle\Manager\SecurityManager'] : $this->load('getSecurityManagerService.php')) && false ?: '_'});
}]);
