<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Util\Helper\Sorting' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Util/Helper/Sorting.php';

return $this->services['AppBundle\Util\Helper\Sorting'] = new \AppBundle\Util\Helper\Sorting();
